// Do not edit. This file is machine generated by the Resource DLL Wizard.

library KBEditor;

{$R *.RES}
{ITE} {LCID:00000409:00000419} {}
{ITE} {DFMFileType} {FMU\dmuData.dfm}
{ITE} {DFMFileType} {FMU\fmuAbout.dfm}
{ITE} {DFMFileType} {FMU\fmuCodes.dfm}
{ITE} {DFMFileType} {FMU\fmuCstKey.dfm}
{ITE} {DFMFileType} {FMU\fmuDevices.dfm}
{ITE} {DFMFileType} {FMU\fmuDoc.dfm}
{ITE} {DFMFileType} {FMU\fmuError.dfm}
{ITE} {DFMFileType} {FMU\fmuFind.dfm}
{ITE} {DFMFileType} {FMU\fmuIButton.dfm}
{ITE} {DFMFileType} {FMU\fmuIButtonKey.dfm}
{ITE} {DFMFileType} {FMU\fmuInfo.dfm}
{ITE} {DFMFileType} {FMU\fmuKey.dfm}
{ITE} {DFMFileType} {FMU\fmuKeyboard.dfm}
{ITE} {DFMFileType} {FMU\fmuKeyLock.dfm}
{ITE} {DFMFileType} {FMU\fmuLog.dfm}
{ITE} {DFMFileType} {FMU\fmuMain.dfm}
{ITE} {DFMFileType} {FMU\fmuMessageWindow.dfm}
{ITE} {DFMFileType} {FMU\fmuMSR.dfm}
{ITE} {DFMFileType} {FMU\fmuNotes.dfm}
{ITE} {DFMFileType} {FMU\fmuPicture.dfm}
{ITE} {DFMFileType} {FMU\fmuPreview.dfm}
{ITE} {DFMFileType} {FMU\fmuProgress.dfm}
{ITE} {DFMFileType} {FMU\fmuReplace.dfm}
{ITE} {DFMFileType} {FMU\fmuScrollWheel.dfm}
{ITE} {DFMFileType} {FMU\fmuSettings.dfm}
{ITE} {DFMFileType} {FMU\fmuStdKey.dfm}
{ITE} {DFMFileType} {FMU\fmuTest.dfm}
{ITE} {DFMFileType} {FMU\fmuUpdates.dfm}
{ITE} {DFMFileType} {FMU\MainDockForm.dfm}
{ITE} {RCFileType} {KBEditor_DRC.rc}

{$R 'FMU\dmuData.dfm' dmData:TDataModule}
{$R 'FMU\fmuAbout.dfm' fmAbout:TForm(SizeableForm)}
{$R 'FMU\fmuCodes.dfm' fmCodes:TForm(SizeableForm)}
{$R 'FMU\fmuCstKey.dfm' fmCstKey:TForm(SizeableForm)}
{$R 'FMU\fmuDevices.dfm' fmDevices:TForm(SizeableForm)}
{$R 'FMU\fmuDoc.dfm' fmDoc:TForm(SizeableForm)}
{$R 'FMU\fmuError.dfm' fmError:TForm(SizeableForm)}
{$R 'FMU\fmuFind.dfm' fmFind:TForm(SizeableForm)}
{$R 'FMU\fmuIButton.dfm' fmIButton:TForm(SizeableForm)}
{$R 'FMU\fmuIButtonKey.dfm' fmIButtonKey:TForm(SizeableForm)}
{$R 'FMU\fmuInfo.dfm' fmInfo:TForm(SizeableForm)}
{$R 'FMU\fmuKey.dfm' fmKeyDlg:TForm(SizeableForm)}
{$R 'FMU\fmuKeyboard.dfm' fmKeyboard:TForm(SizeableForm)}
{$R 'FMU\fmuKeyLock.dfm' fmKeyLock:TForm(SizeableForm)}
{$R 'FMU\fmuLog.dfm' fmLog:TForm(SizeableForm)}
{$R 'FMU\fmuMain.dfm' fmMain:TForm(MainDockForm)}
{$R 'FMU\fmuMessageWindow.dfm' fmMessageWindow:TForm(DockableForm)}
{$R 'FMU\fmuMSR.dfm' fmMSR:TForm(SizeableForm)}
{$R 'FMU\fmuNotes.dfm' fmNotes:TForm(SizeableForm)}
{$R 'FMU\fmuPicture.dfm' fmPicture:TForm(SizeableForm)}
{$R 'FMU\fmuPreview.dfm' fmPreview:TForm(SizeableForm)}
{$R 'FMU\fmuProgress.dfm' fmProgress:TForm(SizeableForm)}
{$R 'FMU\fmuReplace.dfm' fmReplace:TForm(SizeableForm)}
{$R 'FMU\fmuScrollWheel.dfm' fmScrollWheel:TForm(SizeableForm)}
{$R 'FMU\fmuSettings.dfm' fmSettings:TForm(SizeableForm)}
{$R 'FMU\fmuStdKey.dfm' fmStdKey:TForm(SizeableForm)}
{$R 'FMU\fmuTest.dfm' fmTest:TForm(SizeableForm)}
{$R 'FMU\fmuUpdates.dfm' fmUpdates:TForm(SizeableForm)}
{$R 'FMU\MainDockForm.dfm' MainDockForm:TForm(SizeableForm)}
{$R 'KBEditor_DRC.res' 'KBEditor_DRC.rc'}

{$E RUS}

begin
end.