// Do not edit. This file is machine generated by the Resource DLL Wizard.

library KBTest;

{$R *.RES}
{ITE} {LCID:00000419:00000419} {}
{ITE} {DFMFileType} {I\Projects\KBEditor\src\KBEditor\FMU\fmuError.dfm}
{ITE} {DFMFileType} {I\Projects\KBEditor\src\KBEditor\FMU\MainDockForm.dfm}
{ITE} {DFMFileType} {Fmu\dmuData.dfm}
{ITE} {DFMFileType} {Fmu\fmuDevice.dfm}
{ITE} {DFMFileType} {Fmu\fmuEnd.dfm}
{ITE} {DFMFileType} {Fmu\fmuFirmware.dfm}
{ITE} {DFMFileType} {Fmu\fmuIButton.dfm}
{ITE} {DFMFileType} {Fmu\fmuKeyLock.dfm}
{ITE} {DFMFileType} {Fmu\fmuKeysTest.dfm}
{ITE} {DFMFileType} {Fmu\fmuKeyView.dfm}
{ITE} {DFMFileType} {Fmu\fmuLayout.dfm}
{ITE} {DFMFileType} {Fmu\fmuLeds.dfm}
{ITE} {DFMFileType} {Fmu\fmuMain.dfm}
{ITE} {DFMFileType} {Fmu\fmuModel.dfm}
{ITE} {DFMFileType} {Fmu\fmuMSR.dfm}
{ITE} {DFMFileType} {Fmu\fmuScrollWheel.dfm}
{ITE} {DFMFileType} {Fmu\fmuShorting.dfm}
{ITE} {DFMFileType} {Fmu\fmuSound.dfm}
{ITE} {DFMFileType} {Fmu\fmuStart.dfm}
{ITE} {DFMFileType} {Fmu\fmuTestLayout.dfm}
{ITE} {RCFileType} {KBTest_DRC.rc}

{$R 'I\Projects\KBEditor\src\KBEditor\FMU\fmuError.dfm' fmError:TForm(SizeableForm)}
{$R 'I\Projects\KBEditor\src\KBEditor\FMU\MainDockForm.dfm' MainDockForm:TForm(SizeableForm)}
{$R 'Fmu\dmuData.dfm' dmData:TDataModule}
{$R 'Fmu\fmuDevice.dfm' fmDevice:TForm(WizardPage)}
{$R 'Fmu\fmuEnd.dfm' fmEnd:TForm(WizardPage)}
{$R 'Fmu\fmuFirmware.dfm' fmFirmware:TForm(WizardPage)}
{$R 'Fmu\fmuIButton.dfm' fmIButton:TForm(WizardPage)}
{$R 'Fmu\fmuKeyLock.dfm' fmKeyLock:TForm(WizardPage)}
{$R 'Fmu\fmuKeysTest.dfm' fmKeysTest:TForm(WizardPage)}
{$R 'Fmu\fmuKeyView.dfm' fmKeyView:TForm(SizeableForm)}
{$R 'Fmu\fmuLayout.dfm' fmLayout:TForm(WizardPage)}
{$R 'Fmu\fmuLeds.dfm' fmLeds:TForm(WizardPage)}
{$R 'Fmu\fmuMain.dfm' fmMain:TForm(SizeableForm)}
{$R 'Fmu\fmuModel.dfm' fmModel:TForm(WizardPage)}
{$R 'Fmu\fmuMSR.dfm' fmMSR:TForm(WizardPage)}
{$R 'Fmu\fmuScrollWheel.dfm' fmScrollWheel:TForm(WizardPage)}
{$R 'Fmu\fmuShorting.dfm' fmShorting:TForm(WizardPage)}
{$R 'Fmu\fmuSound.dfm' fmSound:TForm(WizardPage)}
{$R 'Fmu\fmuStart.dfm' fmStart:TForm(WizardPage)}
{$R 'Fmu\fmuTestLayout.dfm' fmTestLayout:TForm(WizardPage)}
{$R 'KBTest_DRC.res' 'KBTest_DRC.rc'}

{$E RUS}

begin
end.