program KBTest;

uses
  Forms,
  Windows,
  SysUtils,
  fmuMain in 'Fmu\fmuMain.pas' {fmMain},
  fmuKeyView in 'Fmu\fmuKeyView.pas' {fmKeyView},
  fmuFirmware in 'Fmu\fmuFirmware.pas' {fmFirmware},
  fmuKeysTest in 'Fmu\fmuKeysTest.pas' {fmKeysTest},
  fmuLeds in 'Fmu\fmuLeds.pas' {fmLeds},
  fmuSound in 'Fmu\fmuSound.pas' {fmSound},
  KeyGrid2 in 'Units\KeyGrid2.pas',
  DriverUtils in '..\Common\DriverUtils.pas',
  EMFLayout in '..\Common\EMFLayout.pas',
  Grids2 in '..\Common\Grids2.pas',
  GridType in '..\Common\GridType.pas',
  Hid in '..\Common\HID.pas',
  InitialCheck in '..\Common\InitialCheck.pas',
  KBLayout in '..\Common\KBLayout.pas',
  KBLayoutPrint in '..\Common\KBLayoutPrint.pas',
  KeyboardTypes in '..\Common\KeyboardTypes.pas',
  KeyboardManager in '..\Common\KeyboardManager.pas',
  KeyGrid in '..\Common\KeyGrid.pas',
  LayoutFormat in '..\Common\LayoutFormat.pas',
  LogMessage in '..\Common\LogMessage.pas',
  ModuleLoader in '..\Common\ModuleLoader.pas',
  WizardPage in 'Units\WizardPage.pas',
  Preview in '..\Common\Preview.pas',
  Scanf in '..\Common\Scanf.pas',
  untVInfo in '..\Common\untVInfo.pas',
  Utils in '..\Common\Utils.pas',
  XMLLayout in '..\Common\XMLLayout.pas',
  XmlParser in '..\Common\XMLParser.pas',
  fmuEnd in 'Fmu\fmuEnd.pas' {fmEnd},
  fmuTestLayout in 'Fmu\fmuTestLayout.pas' {fmTestLayout},
  fmuShorting in 'Fmu\fmuShorting.pas' {fmShorting},
  fmuIButton in 'Fmu\fmuIButton.pas' {fmIButton},
  fmuLayout in 'Fmu\fmuLayout.pas' {fmLayout},
  fmuStart in 'Fmu\fmuStart.pas' {fmStart},
  KeyboardController in '..\Common\KeyboardController.pas',
  VirtualKeys in '..\Common\VirtualKeys.pas',
  fmuScrollWheel in 'Fmu\fmuScrollWheel.pas' {fmScrollWheel},
  AppSettings in '..\Common\AppSettings.pas',
  DockableForm in '..\Common\DockableForm.pas',
  ErrorReport in '..\Common\ErrorReport.pas',
  HelpFile in '..\Common\HelpFile.pas',
  HttpGet in '..\Common\HTTPGet.pas',
  LayoutReader in '..\Common\LayoutReader.pas',
  msxml in '..\Common\msxml.pas',
  Page in '..\Common\Page.pas',
  XmlCodeTables in '..\Common\XmlCodeTables.pas',
  MainDockForm in '..\KBEditor\FMU\MainDockForm.pas' {MainDockForm},
  fmuError in '..\KBEditor\FMU\fmuError.pas' {fmError},
  fmuDevice in 'Fmu\fmuDevice.pas' {fmDevice},
  fmuModel in 'Fmu\fmuModel.pas' {fmModel},
  xmlKeyboard in '..\Common\xmlKeyboard.pas',
  uProgress in '..\Common\uProgress.pas',
  ChangeNotifier in '..\Common\ChangeNotifier.pas',
  DeviceError in '..\Common\DeviceError.pas',
  DebugUtils in '..\Common\DebugUtils.pas',
  Keyboard in '..\Common\Keyboard.pas',
  FileUtils in '..\Common\FileUtils.pas',
  BinLayout28 in '..\Common\BinLayout28.pas',
  BinStream in '..\Common\BinStream.pas',
  BinLayout13 in '..\Common\BinLayout13.pas',
  BinLayout30 in '..\Common\BinLayout30.pas',
  SizeableForm in '..\Common\SizeableForm.pas',
  fmuKeyLock in 'Fmu\fmuKeyLock.pas' {fmKeyLock},
  DeviceInfoSet in '..\Common\DeviceInfoSet.pas',
  HidKeyboard in '..\Common\HidKeyboard.pas',
  KeyboardDevice in '..\Common\KeyboardDevice.pas',
  KeyEditor in '..\Common\KeyEditor.pas',
  PS2Keyboard in '..\Common\PS2Keyboard.pas',
  fmuMSR in 'Fmu\fmuMSR.pas' {fmMSR},
  XMLLayoutEng in '..\Common\XMLLayoutEng.pas',
  XmlLayoutRus in '..\Common\XMLLayoutRus.pas',
  AppTypes in '..\Common\AppTypes.pas',
  Semaphore in '..\Common\Semaphore.pas',
  KeyboardProgramXml in 'Units\KeyboardProgramXml.pas',
  KeyboardProgram in 'Units\KeyboardProgram.pas',
  TestWizard in 'Units\TestWizard.pas',
  OperationThread in '..\Common\OperationThread.pas',
  NotifyThread in '..\Common\NotifyThread.pas',
  OperationInterface in '..\Common\OperationInterface.pas',
  WriteFirmwareFileOperation in '..\Common\WriteFirmwareFileOperation.pas',
  WriteLayoutOperation in '..\Common\WriteLayoutOperation.pas',
  StringUtils in '..\Common\StringUtils.pas',
  AppMessages in '..\Common\AppMessages.pas',
  KeyboardFrame in '..\Common\KeyboardFrame.pas',
  dmuData in 'Fmu\dmuData.pas' {dmData: TDataModule},
  KeyboardDriver in '..\Common\KeyboardDriver.pas',
  MockKeyboardDriver in '..\Common\MockKeyboardDriver.pas',
  LogFile in '..\Common\LogFile.pas';

{$R *.RES}

begin
  Application.Initialize;
  Application.CreateForm(TfmMain, fmMain);
  Application.CreateForm(TfmKeyView, fmKeyView);
  Application.CreateForm(TfmError, fmError);
  Application.CreateForm(TdmData, dmData);
  Application.Run;
end.
