ru.AppPublisher=ШТРИХ-М
ru.AppComments=Торговое оборудование от производителя, автоматизация торговли
ru.AppCopyright=Copyright © 2008 ШТРИХ-М®
ru.DefaultDirName=\ШТРИХ-М\KBEditor
ru.DefaultGroupName=ШТРИХ-М\KBEditor
ru.VersionInfoDescription=Драйверы LightPOS-Pro
ru.HistoryIcon=История версий
ru.LPLineDisplayTstIcon=Тест дисплея покупателя
ru.LineDisplayDllIcon=Драйвер дисплея покупателя
ru.LineDisplayInterfaceIcon=Протокол дисплея покупателя
ru.Uninstall=Удалить
ru.StartApplication=Запустить тест драйвера
ru.AppID=LightPOSProRus
ru.HistoryFileName=Doc\ru\History.txt
ru.LineDisplayDllpdf=\Doc\ru\LineDisplayDll.pdf
ru.LineDisplayInterfacepdf=\Doc\ru\LineDisplayInterface.pdf

