//==============================================
//      File rdelphirus.inc
//
//      Русификация Delphi и Kylix.
//
//      Copyright 2005 Polaris Software
//      http://polesoft.da.ru
//      mailto: PolarisLib@mail.ru
//==============================================

//--- интерпретация констант DbConsts.STextFalse, DbConsts.STextTrue
// удалите точку для замены True/False на 1/0
{.$DEFINE STEXT10}