program DeviceTest;

uses
  TestFramework,
  TextTestRunner,
  GUITestRunner,
  HidKeyboardTest in 'Units\HidKeyboardTest.pas',
  DriverUtils in '..\..\Src\Common\DriverUtils.pas',
  EMFLayout in '..\..\Src\Common\EMFLayout.pas',
  Grids2 in '..\..\Src\Common\Grids2.pas',
  GridType in '..\..\Src\Common\GridType.pas',
  Hid in '..\..\Src\Common\HID.pas',
  InitialCheck in '..\..\Src\Common\InitialCheck.pas',
  KBLayout in '..\..\Src\Common\KBLayout.pas',
  KBLayoutPrint in '..\..\Src\Common\KBLayoutPrint.pas',
  KeyboardTypes in '..\..\src\Common\KeyboardTypes.pas',
  KeyboardManager in '..\..\Src\Common\KeyboardManager.pas',
  KeyGrid in '..\..\Src\Common\KeyGrid.pas',
  LayoutFormat in '..\..\Src\Common\LayoutFormat.pas',
  LogMessage in '..\..\Src\Common\LogMessage.pas',
  ModuleLoader in '..\..\Src\Common\ModuleLoader.pas',
  Page in '..\..\Src\Common\Page.pas',
  Preview in '..\..\Src\Common\Preview.pas',
  Scanf in '..\..\Src\Common\Scanf.pas',
  untVInfo in '..\..\Src\Common\untVInfo.pas',
  Utils in '..\..\Src\Common\Utils.pas',
  XMLLayout in '..\..\Src\Common\XMLLayout.pas',
  XmlParser in '..\..\Src\Common\XMLParser.pas',
  KeyboardController in '..\..\Src\Common\KeyboardController.pas',
  msxml in '..\..\Src\Common\MSXML.pas',
  XmlCodeTables in '..\..\Src\Common\XmlCodeTables.pas',
  AppSettings in '..\..\Src\Common\AppSettings.pas',
  uProgress in '..\..\Src\Common\uProgress.pas',
  ChangeNotifier in '..\..\Src\Common\ChangeNotifier.pas',
  xmlKeyboard in '..\..\Src\Common\xmlKeyboard.pas',
  DeviceError in '..\..\Src\Common\DeviceError.pas',
  DebugUtils in '..\..\Src\Common\DebugUtils.pas',
  SizeableForm in '..\..\Src\Common\SizeableForm.pas',
  BinLayout28 in '..\..\Src\Common\BinLayout28.pas',
  BinLayout13 in '..\..\Src\Common\BinLayout13.pas',
  BinLayout30 in '..\..\Src\Common\BinLayout30.pas',
  BinStream in '..\..\Src\Common\BinStream.pas',
  Keyboard in '..\..\Src\Common\Keyboard.pas',
  KeyboardDevice in '..\..\Src\Common\KeyboardDevice.pas',
  HidKeyboard in '..\..\Src\Common\HidKeyboard.pas',
  PS2Keyboard in '..\..\Src\Common\PS2Keyboard.pas',
  DeviceInfoSet in '..\..\Src\Common\DeviceInfoSet.pas',
  XMLLayoutEng in '..\..\src\Common\XMLLayoutEng.pas',
  AppTypes in '..\..\src\Common\AppTypes.pas',
  XmlLayoutRus in '..\..\src\Common\XMLLayoutRus.pas',
  FileUtils in '..\..\src\Common\FileUtils.pas',
  FormFileTest in '..\Shared\FormFileTest.pas',
  LogFile in '..\..\src\Common\LogFile.pas',
  Semaphore in '..\..\src\Common\Semaphore.pas',
  StringUtils in '..\..\src\Common\StringUtils.pas',
  AppMessages in '..\..\src\Common\AppMessages.pas',
  PS2KeyboardTest in 'Units\PS2KeyboardTest.pas',
  KeyboardFrame in '..\..\src\Common\KeyboardFrame.pas',
  KeyboardDriver in '..\..\src\Common\KeyboardDriver.pas',
  MockKeyboardDriver in '..\..\src\Common\MockKeyboardDriver.pas';

{$R *.RES}

begin
  GUITestRunner.RunTest(RegisteredTests);
end.
